flake8_codigos = {
    "E101": "Indentação contém mistura de espaços e tabulações.",
    "E111": "Indentação não é múltiplo de quatro.",
    "E112": "Esperado um bloco indentado.",
    "E113": "Indentação inesperada.",
    "E114": "Indentação não é múltiplo de quatro (comentário).",
    "E115": "Esperado um bloco indentado (comentário).",
    "E116": "Indentação inesperada (comentário).",
    "E117": "Indentação excessiva.",
    "E121": "Linha de continuação subindentada para indentação suspensa.",
    "E122": "Linha de continuação sem indentação ou com indentação negativa.",
    "E123": "Colchete de fechamento não corresponde à indentação.",
    "E124": "Colchete de fechamento não corresponde à indentação visual.",
    "E125": "Linha de continuação com mesma indentação da próxima linha lógica.",
    "E126": "Linha de continuação com indentação excessiva para indentação suspensa.",
    "E127": "Linha de continuação com indentação excessiva para indentação visual.",
    "E128": "Linha de continuação com pouca indentação para indentação visual.",
    "E129": "Linha visualmente indentada com mesma indentação da próxima linha lógica.",
    "E131": "Linha de continuação desalinhada para indentação suspensa.",
    "E133": "Colchete de fechamento está sem indentação esperada.",
    "E201": "Espaço em branco após '('.",
    "E202": "Espaço em branco antes de ')'.",
    "E203": "Espaço em branco antes de ':'.",
    "E211": "Espaço em branco antes de '('.",
    "E221": "Múltiplos espaços antes de operador.",
    "E222": "Múltiplos espaços após operador.",
    "E223": "Tabulação antes de operador.",
    "E224": "Tabulação após operador.",
    "E225": "Falta espaço em branco ao redor de operador.",
    "E226": "Falta espaço em branco ao redor de operador aritmético.",
    "E227": "Falta espaço em branco ao redor de operador bitwise ou shift.",
    "E228": "Falta espaço em branco ao redor de operador de módulo.",
    "E231": "Falta espaço em branco após ',', ';' ou ':'.",
    "E241": "Múltiplos espaços após ','.",
    "E242": "Tabulação após ','.",
    "E251": "Espaços inesperados ao redor de '=' usado para argumentos nomeados.",
    "E261": "Mínimo de duas espaços antes de comentário em linha.",
    "E262": "Comentário em linha deve começar com '# '.",
    "E265": "Comentário de bloco deve começar com '# '.",
    "E266": "Muitos '#' no início do comentário.",
    "E271": "Múltiplos espaços após palavra-chave.",
    "E272": "Múltiplos espaços antes de palavra-chave.",
    "E273": "Tabulação após palavra-chave.",
    "E274": "Tabulação antes de palavra-chave.",
    "E275": "Falta espaço em branco após palavra-chave.",
    "E301": "Esperado 1 linha em branco antes da definição.",
    "E302": "Esperado 2 linhas em branco antes da definição.",
    "E303": "Linhas em branco demais (máximo permitido excedido).",
    "E304": "Linhas em branco após decorador de função.",
    "E305": "Esperado 2 linhas em branco após definição de função ou classe.",
    "E306": "Esperado 1 linha em branco antes de definição aninhada.",
    "E401": "Múltiplas importações na mesma linha.",
    "E402": "Importação em nível de módulo não está no topo do arquivo.",
    "E501": "Linha muito longa.",
    "E502": "Barra invertida redundante entre colchetes.",
    "E701": "Múltiplas instruções na mesma linha (uso de dois-pontos).",
    "E702": "Múltiplas instruções na mesma linha (uso de ponto e vírgula).",
    "E703": "Instrução termina com ponto e vírgula.",
    "E704": "Múltiplas instruções na mesma linha (definição de função).",
    "E711": "Comparação com None deve ser feita com 'is None'.",
    "E712": "Comparação com True/False deve ser simplificada.",
    "E713": "Teste de associação deve ser feito com 'not in'.",
    "E714": "Teste de identidade de objeto deve ser feito com 'is not'.",
    "E721": "Evite comparar tipos diretamente, use isinstance().",
    "E722": "Evite usar except vazio (sem tipo de exceção).",
    "E731": "Evite atribuir expressões lambda diretamente.",
    "E741": "Evite nomes de variável de letra única como 'I', 'O', 'l'.",
    "E901": "Erro de sintaxe ou de indentação.",
    "E902": "Erro de IO ao acessar arquivo.",
    "E999": "Erro de sintaxe durante parsing AST.",
    "W191": "Indentação contém tabulações.",
    "W291": "Espaço em branco no final da linha.",
    "W292": "Arquivo não termina com nova linha.",
    "W293": "Linha em branco contém espaços.",
    "W391": "Linha em branco no final do arquivo.",
    "W503": "Quebra de linha antes de operador binário.",
    "W504": "Quebra de linha após operador binário.",
    "W605": "Sequência de escape inválida.",
    "F401": "Módulo importado mas não utilizado.",
    "F403": "'from module import *' utilizado.",
    "F405": "Nome indefinido possivelmente devido a importação global.",
    "F821": "Nome indefinido.",
    "F841": "Variável local atribuída mas nunca usada.",
    "C901": "Função com complexidade ciclomática alta."
}
